package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingRoom generated by hbm2java
 */
@Entity
@Table(name="BookingRoom"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class BookingRoom  implements java.io.Serializable {


     private Integer id;
     private Accounts accounts;
     private Customers customers;
     private Integer numOfChildren;
     private Integer numOfAdult;
     private Date dateIn;
     private Date dateOut;
     private BigDecimal advance;
     private Set<BookedRooms> bookedRoomses = new HashSet<BookedRooms>(0);

    public BookingRoom() {
    }

	
    public BookingRoom(Accounts accounts, Customers customers) {
        this.accounts = accounts;
        this.customers = customers;
    }
    public BookingRoom(Accounts accounts, Customers customers, Integer numOfChildren, Integer numOfAdult, Date dateIn, Date dateOut, BigDecimal advance, Set<BookedRooms> bookedRoomses) {
       this.accounts = accounts;
       this.customers = customers;
       this.numOfChildren = numOfChildren;
       this.numOfAdult = numOfAdult;
       this.dateIn = dateIn;
       this.dateOut = dateOut;
       this.advance = advance;
       this.bookedRoomses = bookedRoomses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SellerID", nullable=false)
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CustomerID", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="NumOfChildren")
    public Integer getNumOfChildren() {
        return this.numOfChildren;
    }
    
    public void setNumOfChildren(Integer numOfChildren) {
        this.numOfChildren = numOfChildren;
    }

    
    @Column(name="NumOfAdult")
    public Integer getNumOfAdult() {
        return this.numOfAdult;
    }
    
    public void setNumOfAdult(Integer numOfAdult) {
        this.numOfAdult = numOfAdult;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateIn", length=23)
    public Date getDateIn() {
        return this.dateIn;
    }
    
    public void setDateIn(Date dateIn) {
        this.dateIn = dateIn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOut", length=23)
    public Date getDateOut() {
        return this.dateOut;
    }
    
    public void setDateOut(Date dateOut) {
        this.dateOut = dateOut;
    }

    
    @Column(name="Advance", precision=18)
    public BigDecimal getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(BigDecimal advance) {
        this.advance = advance;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookingRoom")
    public Set<BookedRooms> getBookedRoomses() {
        return this.bookedRoomses;
    }
    
    public void setBookedRoomses(Set<BookedRooms> bookedRoomses) {
        this.bookedRoomses = bookedRoomses;
    }




}


