package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryOfRoom generated by hbm2java
 */
@Entity
@Table(name="CategoryOfRoom"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class CategoryOfRoom  implements java.io.Serializable {


     private Integer id;
     private String cateRoomName;
     private Integer numOfBed;
     private Long size;
     private Long price;
     private Boolean isActive;
     private Set<Rooms> roomses = new HashSet<Rooms>(0);

    public CategoryOfRoom() {
    }

    public CategoryOfRoom(String cateRoomName, Integer numOfBed, Long size, Long price, Boolean isActive, Set<Rooms> roomses) {
       this.cateRoomName = cateRoomName;
       this.numOfBed = numOfBed;
       this.size = size;
       this.price = price;
       this.isActive = isActive;
       this.roomses = roomses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CateRoomName")
    public String getCateRoomName() {
        return this.cateRoomName;
    }
    
    public void setCateRoomName(String cateRoomName) {
        this.cateRoomName = cateRoomName;
    }

    
    @Column(name="NumOfBed")
    public Integer getNumOfBed() {
        return this.numOfBed;
    }
    
    public void setNumOfBed(Integer numOfBed) {
        this.numOfBed = numOfBed;
    }

    
    @Column(name="Size", precision=18, scale=0)
    public Long getSize() {
        return this.size;
    }
    
    public void setSize(Long size) {
        this.size = size;
    }

    
    @Column(name="Price", precision=18, scale=0)
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoryOfRoom")
    public Set<Rooms> getRoomses() {
        return this.roomses;
    }
    
    public void setRoomses(Set<Rooms> roomses) {
        this.roomses = roomses;
    }




}


