package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryOfProduct generated by hbm2java
 */
@Entity
@Table(name="CategoryOfProduct"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class CategoryOfProduct  implements java.io.Serializable {


     private Integer id;
     private String cateName;
     private Boolean isActive;
     private Set<Products> productses = new HashSet<Products>(0);

    public CategoryOfProduct() {
    }

    public CategoryOfProduct(String cateName, Boolean isActive, Set<Products> productses) {
       this.cateName = cateName;
       this.isActive = isActive;
       this.productses = productses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CateName")
    public String getCateName() {
        return this.cateName;
    }
    
    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoryOfProduct")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


