package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "Customers", schema = "dbo", catalog = "Hotel"
)
public class Customers implements java.io.Serializable {

    private Integer customerId;
    private String customerName;
    private String customerAddress;
    private String identityCard;
    private Set<BookingRoom> bookingRooms = new HashSet<BookingRoom>(0);

    public Customers() {
    }

    public Customers(String customerName, String customerAddress, String identityCard, Set<BookingRoom> bookingRooms) {
        this.customerName = customerName;
        this.customerAddress = customerAddress;
        this.identityCard = identityCard;
        this.bookingRooms = bookingRooms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CustomerID", unique = true, nullable = false)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "CustomerName")
    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @Column(name = "CustomerAddress")
    public String getCustomerAddress() {
        return this.customerAddress;
    }

    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    @Column(name = "IdentityCard")
    public String getIdentityCard() {
        return this.identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
    public Set<BookingRoom> getBookingRooms() {
        return this.bookingRooms;
    }

    public void setBookingRooms(Set<BookingRoom> bookingRooms) {
        this.bookingRooms = bookingRooms;
    }

}
