package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Functions generated by hbm2java
 */
@Entity
@Table(name="Functions"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class Functions  implements java.io.Serializable {


     private Integer functionId;
     private String functionName;
     private Boolean isActive;
     private Set<RoleFunction> roleFunctions = new HashSet<RoleFunction>(0);

    public Functions() {
    }

    public Functions(String functionName, Boolean isActive, Set<RoleFunction> roleFunctions) {
       this.functionName = functionName;
       this.isActive = isActive;
       this.roleFunctions = roleFunctions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FunctionID", unique=true, nullable=false)
    public Integer getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    
    @Column(name="FunctionName")
    public String getFunctionName() {
        return this.functionName;
    }
    
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="functions")
    public Set<RoleFunction> getRoleFunctions() {
        return this.roleFunctions;
    }
    
    public void setRoleFunctions(Set<RoleFunction> roleFunctions) {
        this.roleFunctions = roleFunctions;
    }




}


