package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HotelOrderDish generated by hbm2java
 */
@Entity
@Table(name = "HotelOrderDish", schema = "dbo", catalog = "Hotel"
)
public class HotelOrderDish implements java.io.Serializable {

    private Integer id;
    private Products products;
    private Rooms rooms;
    private Integer quantity;
    private Boolean isActive;

    public HotelOrderDish() {
    }

    public HotelOrderDish(Products products, Rooms rooms, Integer quantity) {
        this.products = products;
        this.rooms = rooms;
        this.quantity = quantity;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ProductID")
    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        this.products = products;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RoomID")
    public Rooms getRooms() {
        return this.rooms;
    }

    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }

    @Column(name = "Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

}
