package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HotelOrderService generated by hbm2java
 */
@Entity
@Table(name="HotelOrderService"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class HotelOrderService  implements java.io.Serializable {


     private Integer id;
     private Rooms rooms;
     private Services services;
     private Integer quantity;

    public HotelOrderService() {
    }

    public HotelOrderService(Rooms rooms, Services services, Integer quantity) {
       this.rooms = rooms;
       this.services = services;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoomID")
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ServiceID")
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


