package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderTable generated by hbm2java
 */
@Entity
@Table(name="OrderTable"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class OrderTable  implements java.io.Serializable {


     private Integer id;
     private Accounts accounts;
     private CustomerOrderTable customerOrderTable;
     private RestaurantTable restaurantTable;
     private Date dateOrder;
     private Date dateIn;

    public OrderTable() {
    }

    public OrderTable(Accounts accounts, CustomerOrderTable customerOrderTable, RestaurantTable restaurantTable, Date dateOrder, Date dateIn) {
       this.accounts = accounts;
       this.customerOrderTable = customerOrderTable;
       this.restaurantTable = restaurantTable;
       this.dateOrder = dateOrder;
       this.dateIn = dateIn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StaffID")
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CustomerID")
    public CustomerOrderTable getCustomerOrderTable() {
        return this.customerOrderTable;
    }
    
    public void setCustomerOrderTable(CustomerOrderTable customerOrderTable) {
        this.customerOrderTable = customerOrderTable;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TableID")
    public RestaurantTable getRestaurantTable() {
        return this.restaurantTable;
    }
    
    public void setRestaurantTable(RestaurantTable restaurantTable) {
        this.restaurantTable = restaurantTable;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOrder", length=23)
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateIn", length=23)
    public Date getDateIn() {
        return this.dateIn;
    }
    
    public void setDateIn(Date dateIn) {
        this.dateIn = dateIn;
    }




}


