package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderedService generated by hbm2java
 */
@Entity
@Table(name = "OrderedService", schema = "dbo", catalog = "Hotel"
)
public class OrderedService implements java.io.Serializable {

    private Integer id;
    private Accounts accounts;
    private CustomerOrderService customerOrderService;
    private Services services;
    private Integer orderId;
    private Integer quantity;
    private Date dateOrder;

    public OrderedService() {
    }

    public OrderedService(Accounts accounts, CustomerOrderService customerOrderService, Services services, Integer orderId, Integer quantity, Date dateOrder) {
        this.accounts = accounts;
        this.customerOrderService = customerOrderService;
        this.services = services;
        // this.orderId = orderId;
        this.quantity = quantity;
        this.dateOrder = dateOrder;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SellerID")
    public Accounts getAccounts() {
        return this.accounts;
    }

    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CustomerID")
    public CustomerOrderService getCustomerOrderService() {
        return this.customerOrderService;
    }

    public void setCustomerOrderService(CustomerOrderService customerOrderService) {
        this.customerOrderService = customerOrderService;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ServiceID")
    public Services getServices() {
        return this.services;
    }

    public void setServices(Services services) {
        this.services = services;
    }

    @Column(name="OrderID")
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    @Column(name = "Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DateOrder", length = 23)
    public Date getDateOrder() {
        return this.dateOrder;
    }

    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }

}
