package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderedDishes generated by hbm2java
 */
@Entity
@Table(name="OrderedDishes"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class OrderedDishes  implements java.io.Serializable {


     private Integer id;
     private Products products;
     private RestaurantBill restaurantBill;
     private Integer quantity;

    public OrderedDishes() {
    }

    public OrderedDishes(Products products, RestaurantBill restaurantBill, Integer quantity) {
       this.products = products;
       this.restaurantBill = restaurantBill;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductID")
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BillID")
    public RestaurantBill getRestaurantBill() {
        return this.restaurantBill;
    }
    
    public void setRestaurantBill(RestaurantBill restaurantBill) {
        this.restaurantBill = restaurantBill;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


