package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="Products"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class Products  implements java.io.Serializable {


     private Integer productId;
     private CategoryOfProduct categoryOfProduct;
     private Suppliers suppliers;
     private Units units;
     private String productName;
     private Integer quantity;
     private Date importDate;
     private Boolean isActive;
     private BigDecimal price;
     private Set<HotelOrderDish> hotelOrderDishes = new HashSet<HotelOrderDish>(0);
     private Set<OrderedDishes> orderedDisheses = new HashSet<OrderedDishes>(0);

    public Products() {
    }

    public Products(CategoryOfProduct categoryOfProduct, Suppliers suppliers, Units units, String productName, Integer quantity, Date importDate, Boolean isActive, BigDecimal price, Set<HotelOrderDish> hotelOrderDishes, Set<OrderedDishes> orderedDisheses) {
       this.categoryOfProduct = categoryOfProduct;
       this.suppliers = suppliers;
       this.units = units;
       this.productName = productName;
       this.quantity = quantity;
       this.importDate = importDate;
       this.isActive = isActive;
       this.price = price;
       this.hotelOrderDishes = hotelOrderDishes;
       this.orderedDisheses = orderedDisheses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ProductID", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CateID")
    public CategoryOfProduct getCategoryOfProduct() {
        return this.categoryOfProduct;
    }
    
    public void setCategoryOfProduct(CategoryOfProduct categoryOfProduct) {
        this.categoryOfProduct = categoryOfProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SupplierID")
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UnitID")
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }

    
    @Column(name="ProductName")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportDate", length=23)
    public Date getImportDate() {
        return this.importDate;
    }
    
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Price", precision=18)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<HotelOrderDish> getHotelOrderDishes() {
        return this.hotelOrderDishes;
    }
    
    public void setHotelOrderDishes(Set<HotelOrderDish> hotelOrderDishes) {
        this.hotelOrderDishes = hotelOrderDishes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<OrderedDishes> getOrderedDisheses() {
        return this.orderedDisheses;
    }
    
    public void setOrderedDisheses(Set<OrderedDishes> orderedDisheses) {
        this.orderedDisheses = orderedDisheses;
    }




}


