package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RestaurantTable generated by hbm2java
 */
@Entity
@Table(name="RestaurantTable"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class RestaurantTable  implements java.io.Serializable {


     private Integer tableId;
     private Integer status;
     private Boolean isActive;
     private Integer numOfChairs;
     private String description;
     private Set<OrderTable> orderTables = new HashSet<OrderTable>(0);
     private Set<RestaurantBill> restaurantBills = new HashSet<RestaurantBill>(0);

    public RestaurantTable() {
    }

    public RestaurantTable(Integer status, Boolean isActive, Integer numOfChairs, String description, Set<OrderTable> orderTables, Set<RestaurantBill> restaurantBills) {
       this.status = status;
       this.isActive = isActive;
       this.numOfChairs = numOfChairs;
       this.description = description;
       this.orderTables = orderTables;
       this.restaurantBills = restaurantBills;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TableID", unique=true, nullable=false)
    public Integer getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    
    @Column(name="Status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="NumOfChairs")
    public Integer getNumOfChairs() {
        return this.numOfChairs;
    }
    
    public void setNumOfChairs(Integer numOfChairs) {
        this.numOfChairs = numOfChairs;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="restaurantTable")
    public Set<OrderTable> getOrderTables() {
        return this.orderTables;
    }
    
    public void setOrderTables(Set<OrderTable> orderTables) {
        this.orderTables = orderTables;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="restaurantTable")
    public Set<RestaurantBill> getRestaurantBills() {
        return this.restaurantBills;
    }
    
    public void setRestaurantBills(Set<RestaurantBill> restaurantBills) {
        this.restaurantBills = restaurantBills;
    }




}


