package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RestaurantBill generated by hbm2java
 */
@Entity
@Table(name="RestaurantBill"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class RestaurantBill  implements java.io.Serializable {


     private Integer id;
     private Accounts accounts;
     private RestaurantTable restaurantTable;
     private String customerName;
     private Date date;
     private BigDecimal total;
     private Set<OrderedDishes> orderedDisheses = new HashSet<OrderedDishes>(0);

    public RestaurantBill() {
    }

    public RestaurantBill(Accounts accounts, RestaurantTable restaurantTable, String customerName, Date date, BigDecimal total, Set<OrderedDishes> orderedDisheses) {
       this.accounts = accounts;
       this.restaurantTable = restaurantTable;
       this.customerName = customerName;
       this.date = date;
       this.total = total;
       this.orderedDisheses = orderedDisheses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StaffID")
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TableID")
    public RestaurantTable getRestaurantTable() {
        return this.restaurantTable;
    }
    
    public void setRestaurantTable(RestaurantTable restaurantTable) {
        this.restaurantTable = restaurantTable;
    }

    
    @Column(name="CustomerName")
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date", length=23)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="Total", precision=18)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="restaurantBill")
    public Set<OrderedDishes> getOrderedDisheses() {
        return this.orderedDisheses;
    }
    
    public void setOrderedDisheses(Set<OrderedDishes> orderedDisheses) {
        this.orderedDisheses = orderedDisheses;
    }




}


