package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleFunction generated by hbm2java
 */
@Entity
@Table(name="Role_Function"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class RoleFunction  implements java.io.Serializable {


     private Integer id;
     private Functions functions;
     private Roles roles;

    public RoleFunction() {
    }

    public RoleFunction(Functions functions, Roles roles) {
       this.functions = functions;
       this.roles = roles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FunctionID")
    public Functions getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(Functions functions) {
        this.functions = functions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoleID")
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


