package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table(name="Rooms"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class Rooms  implements java.io.Serializable {


     private Integer roomId;
     private CategoryOfRoom categoryOfRoom;
     private String roomName;
     private Integer floor;
     private Integer status;
     private Boolean isActive;
     private Set<HotelOrderDish> hotelOrderDishes = new HashSet<HotelOrderDish>(0);
     private Set<HotelOrderService> hotelOrderServices = new HashSet<HotelOrderService>(0);
     private Set<BookedRooms> bookedRoomses = new HashSet<BookedRooms>(0);

    public Rooms() {
    }

    public Rooms(CategoryOfRoom categoryOfRoom, String roomName, Integer floor, Integer status, Boolean isActive, Set<HotelOrderDish> hotelOrderDishes, Set<HotelOrderService> hotelOrderServices, Set<BookedRooms> bookedRoomses) {
       this.categoryOfRoom = categoryOfRoom;
       this.roomName = roomName;
       this.floor = floor;
       this.status = status;
       this.isActive = isActive;
       this.hotelOrderDishes = hotelOrderDishes;
       this.hotelOrderServices = hotelOrderServices;
       this.bookedRoomses = bookedRoomses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RoomID", unique=true, nullable=false)
    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CateID")
    public CategoryOfRoom getCategoryOfRoom() {
        return this.categoryOfRoom;
    }
    
    public void setCategoryOfRoom(CategoryOfRoom categoryOfRoom) {
        this.categoryOfRoom = categoryOfRoom;
    }

    
    @Column(name="RoomName")
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    
    @Column(name="Floor")
    public Integer getFloor() {
        return this.floor;
    }
    
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    
    @Column(name="Status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rooms")
    public Set<HotelOrderDish> getHotelOrderDishes() {
        return this.hotelOrderDishes;
    }
    
    public void setHotelOrderDishes(Set<HotelOrderDish> hotelOrderDishes) {
        this.hotelOrderDishes = hotelOrderDishes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rooms")
    public Set<HotelOrderService> getHotelOrderServices() {
        return this.hotelOrderServices;
    }
    
    public void setHotelOrderServices(Set<HotelOrderService> hotelOrderServices) {
        this.hotelOrderServices = hotelOrderServices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rooms")
    public Set<BookedRooms> getBookedRoomses() {
        return this.bookedRoomses;
    }
    
    public void setBookedRoomses(Set<BookedRooms> bookedRoomses) {
        this.bookedRoomses = bookedRoomses;
    }




}


