package entities;
// Generated Nov 19, 2015 12:30:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name="Services"
    ,schema="dbo"
    ,catalog="Hotel"
)
public class Services  implements java.io.Serializable {


     private Integer serviceId;
     private String serviceName;
     private Boolean isActive;
     private BigDecimal price;
     private Set<OrderedService> orderedServices = new HashSet<OrderedService>(0);
     private Set<HotelOrderService> hotelOrderServices = new HashSet<HotelOrderService>(0);

    public Services() {
    }

    public Services(String serviceName, Boolean isActive, BigDecimal price, Set<OrderedService> orderedServices, Set<HotelOrderService> hotelOrderServices) {
       this.serviceName = serviceName;
       this.isActive = isActive;
       this.price = price;
       this.orderedServices = orderedServices;
       this.hotelOrderServices = hotelOrderServices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ServiceID", unique=true, nullable=false)
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="ServiceName")
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Price", precision=18)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<OrderedService> getOrderedServices() {
        return this.orderedServices;
    }
    
    public void setOrderedServices(Set<OrderedService> orderedServices) {
        this.orderedServices = orderedServices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<HotelOrderService> getHotelOrderServices() {
        return this.hotelOrderServices;
    }
    
    public void setHotelOrderServices(Set<HotelOrderService> hotelOrderServices) {
        this.hotelOrderServices = hotelOrderServices;
    }




}


