/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;

import models.ReportManager;
import utils.Converter;

/**
 *
 * @author Administrator
 */
public class ReportDay extends javax.swing.JFrame {

    /**
     * Creates new form ReportMonth
     */
    ReportManager rpDAO = new ReportManager();
    static ReportDay instance = null;

    public ReportDay() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
    }

    public static ReportDay getIns() {
        if (instance == null) {
            instance = new ReportDay();
        }
        return instance;

    }

    public void setIcon() {
        this.setIconImage(new ImageIcon(getClass().getResource("/image/logoTitle.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblReport = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        bt_Cancel = new javax.swing.JButton();
        bt_Ok = new javax.swing.JButton();
        pnlDate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jxdImportDateGo = new org.jdesktop.swingx.JXDatePicker();
        jxdImportDateTo = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReport.setForeground(new java.awt.Color(0, 0, 204));
        lblReport.setText("REPORT BY DAY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        getContentPane().add(lblReport, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(350, 180));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 180));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        pnlButton.setLayout(new java.awt.GridBagLayout());

        bt_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        bt_Cancel.setText("Exit");
        bt_Cancel.setMaximumSize(new java.awt.Dimension(110, 32));
        bt_Cancel.setMinimumSize(new java.awt.Dimension(110, 32));
        bt_Cancel.setPreferredSize(new java.awt.Dimension(110, 32));
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlButton.add(bt_Cancel, gridBagConstraints);

        bt_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        bt_Ok.setText("Report");
        bt_Ok.setMaximumSize(new java.awt.Dimension(130, 32));
        bt_Ok.setMinimumSize(new java.awt.Dimension(130, 32));
        bt_Ok.setPreferredSize(new java.awt.Dimension(130, 32));
        bt_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlButton.add(bt_Ok, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(pnlButton, gridBagConstraints);

        pnlDate.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("From:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDate.add(jLabel1, gridBagConstraints);

        jLabel2.setText("To: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDate.add(jLabel2, gridBagConstraints);

        jxdImportDateGo.setMaximumSize(new java.awt.Dimension(150, 22));
        jxdImportDateGo.setMinimumSize(new java.awt.Dimension(150, 22));
        jxdImportDateGo.setPreferredSize(new java.awt.Dimension(150, 22));
        jxdImportDateGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdImportDateGoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 0);
        pnlDate.add(jxdImportDateGo, gridBagConstraints);

        jxdImportDateTo.setMaximumSize(new java.awt.Dimension(150, 22));
        jxdImportDateTo.setMinimumSize(new java.awt.Dimension(150, 22));
        jxdImportDateTo.setPreferredSize(new java.awt.Dimension(150, 22));
        jxdImportDateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdImportDateToActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 0);
        pnlDate.add(jxdImportDateTo, gridBagConstraints);

        jPanel3.add(pnlDate, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkActionPerformed
        String daygo = Converter.dateToString(jxdImportDateGo.getDate());
        String dayto = Converter.dateToString(jxdImportDateTo.getDate());
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("datego", daygo);
        param.put("dateto", dayto);
        rpDAO.ReportByDay(param);
    }//GEN-LAST:event_bt_OkActionPerformed

    private void jxdImportDateGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdImportDateGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxdImportDateGoActionPerformed

    private void jxdImportDateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdImportDateToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxdImportDateToActionPerformed

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXDatePicker jxdImportDateGo;
    private org.jdesktop.swingx.JXDatePicker jxdImportDateTo;
    private javax.swing.JLabel lblReport;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDate;
    // End of variables declaration//GEN-END:variables
}
