/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.RestaurantTable;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import models.TableEntityManager;

/**
 *
 * @author Ashley
 */
public class Tables extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tables
     */
    static Tables instance = null;
    List<JPanel> viewList = new ArrayList<>();
    public static List<RestaurantTable> selectedList = new ArrayList<RestaurantTable>();
    TableEntityManager tableModel = new TableEntityManager();

    public Tables() {
        initComponents();
        for (int i = 0; i < selectedList.size(); i++) {
            selectedList.remove(i);
        }
        addViewList();
        loadData();
        setToolTips();
    }

    public static Tables getIns() {
        if (instance == null) {
            instance = new Tables();
        }
        return instance;
    }

    public void setToolTips() {
        tbl1.setToolTipText(tableModel.find(1).getDescription()+"\n Chairs: "+tableModel.find(1).getNumOfChairs().toString());
        tbl2.setToolTipText(tableModel.find(2).getDescription()+"\n Chairs: "+tableModel.find(2).getNumOfChairs().toString());
        tbl3.setToolTipText(tableModel.find(3).getDescription()+"\n Chairs: "+tableModel.find(3).getNumOfChairs().toString());
        tbl4.setToolTipText(tableModel.find(4).getDescription()+"\n Chairs: "+tableModel.find(4).getNumOfChairs().toString());
        tbl5.setToolTipText(tableModel.find(5).getDescription()+"\n Chairs: "+tableModel.find(5).getNumOfChairs().toString());
        tbl6.setToolTipText(tableModel.find(6).getDescription()+"\n Chairs: "+tableModel.find(6).getNumOfChairs().toString());
        tbl7.setToolTipText(tableModel.find(7).getDescription()+"\n Chairs: "+tableModel.find(7).getNumOfChairs().toString());
        tbl8.setToolTipText(tableModel.find(8).getDescription()+"\n Chairs: "+tableModel.find(8).getNumOfChairs().toString());
        tbl9.setToolTipText(tableModel.find(9).getDescription()+"\n Chairs: "+tableModel.find(9).getNumOfChairs().toString());
        tbl10.setToolTipText(tableModel.find(10).getDescription()+" Chairs: \n"+tableModel.find(10).getNumOfChairs().toString());
        tbl11.setToolTipText(tableModel.find(11).getDescription()+"\n  Chairs: "+tableModel.find(11).getNumOfChairs().toString());
        tbl12.setToolTipText(tableModel.find(12).getDescription()+"\n  Chairs: "+tableModel.find(12).getNumOfChairs().toString());
    }

    public void addViewList() {
        viewList.add(tbl1);
        viewList.add(tbl2);
        viewList.add(tbl3);
        viewList.add(tbl4);
        viewList.add(tbl5);
        viewList.add(tbl6);
        viewList.add(tbl7);
        viewList.add(tbl8);
        viewList.add(tbl9);
        viewList.add(tbl10);
        viewList.add(tbl11);
        viewList.add(tbl12);

    }

    public void loadData() {
        List<RestaurantTable> temp = tableModel.getAllFromDB();
        for (int i = 0; i < temp.size(); i++) {
            if (temp.get(i).getStatus() == 2) {
                viewList.get(i).setBackground(Color.yellow);
                viewList.get(i).repaint();

            } else if (temp.get(i).getStatus() == 3) {
                viewList.get(i).setBackground(Color.red);
                viewList.get(i).repaint();
            } else {
                viewList.get(i).setBackground(new Color(0xAFAFAF));
                viewList.get(i).repaint();
            }
        }
    }

    public boolean addToSelectedList(RestaurantTable room) {
        if (selectedList.add(room)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCover = new javax.swing.JPanel();
        tbl1 = new javax.swing.JPanel();
        lblAcc = new javax.swing.JLabel();
        tbl2 = new javax.swing.JPanel();
        lblPermission7 = new javax.swing.JLabel();
        tbl5 = new javax.swing.JPanel();
        lblAcc10 = new javax.swing.JLabel();
        tbl4 = new javax.swing.JPanel();
        lblAcc3 = new javax.swing.JLabel();
        tbl8 = new javax.swing.JPanel();
        lblPermission8 = new javax.swing.JLabel();
        tbl7 = new javax.swing.JPanel();
        lblPermission1 = new javax.swing.JLabel();
        tbl6 = new javax.swing.JPanel();
        lblPermission4 = new javax.swing.JLabel();
        tbl9 = new javax.swing.JPanel();
        lblAcc15 = new javax.swing.JLabel();
        tbl3 = new javax.swing.JPanel();
        lblAcc14 = new javax.swing.JLabel();
        tbl10 = new javax.swing.JPanel();
        lblPermission10 = new javax.swing.JLabel();
        tbl12 = new javax.swing.JPanel();
        lblPermission6 = new javax.swing.JLabel();
        tbl11 = new javax.swing.JPanel();
        lblAcc4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSetAvai = new javax.swing.JButton();

        setTitle("Tables");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlCover.setLayout(new java.awt.GridBagLayout());

        tbl1.setBackground(new java.awt.Color(175, 175, 175));
        tbl1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl1.setToolTipText("Account Management");
        tbl1.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl1.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl1.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl1MouseExited(evt);
            }
        });
        tbl1.setLayout(new java.awt.GridBagLayout());

        lblAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc.setToolTipText("Account Management");
        lblAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccMouseExited(evt);
            }
        });
        tbl1.add(lblAcc, new java.awt.GridBagConstraints());

        pnlCover.add(tbl1, new java.awt.GridBagConstraints());

        tbl2.setBackground(new java.awt.Color(175, 175, 175));
        tbl2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl2.setToolTipText("Permission Management");
        tbl2.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl2.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl2.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl2MouseExited(evt);
            }
        });
        tbl2.setLayout(new java.awt.GridBagLayout());

        lblPermission7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission7.setToolTipText("Permission Management");
        lblPermission7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission7MouseExited(evt);
            }
        });
        tbl2.add(lblPermission7, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlCover.add(tbl2, gridBagConstraints);

        tbl5.setBackground(new java.awt.Color(175, 175, 175));
        tbl5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl5.setToolTipText("Account Management");
        tbl5.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl5.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl5.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl5MouseExited(evt);
            }
        });
        tbl5.setLayout(new java.awt.GridBagLayout());

        lblAcc10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc10.setToolTipText("Account Management");
        lblAcc10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcc10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcc10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcc10MouseExited(evt);
            }
        });
        tbl5.add(lblAcc10, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlCover.add(tbl5, gridBagConstraints);

        tbl4.setBackground(new java.awt.Color(175, 175, 175));
        tbl4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl4.setToolTipText("Account Management");
        tbl4.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl4.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl4.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl4MouseExited(evt);
            }
        });
        tbl4.setLayout(new java.awt.GridBagLayout());

        lblAcc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc3.setToolTipText("Account Management");
        lblAcc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcc3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcc3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcc3MouseExited(evt);
            }
        });
        tbl4.add(lblAcc3, new java.awt.GridBagConstraints());

        pnlCover.add(tbl4, new java.awt.GridBagConstraints());

        tbl8.setBackground(new java.awt.Color(175, 175, 175));
        tbl8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl8.setToolTipText("Account Management");
        tbl8.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl8.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl8.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl8MouseExited(evt);
            }
        });
        tbl8.setLayout(new java.awt.GridBagLayout());

        lblPermission8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission8.setToolTipText("Permission Management");
        lblPermission8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission8MouseExited(evt);
            }
        });
        tbl8.add(lblPermission8, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        pnlCover.add(tbl8, gridBagConstraints);

        tbl7.setBackground(new java.awt.Color(175, 175, 175));
        tbl7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl7.setToolTipText("Permission Management");
        tbl7.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl7.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl7.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl7MouseExited(evt);
            }
        });
        tbl7.setLayout(new java.awt.GridBagLayout());

        lblPermission1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission1.setToolTipText("Permission Management");
        lblPermission1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission1MouseExited(evt);
            }
        });
        tbl7.add(lblPermission1, new java.awt.GridBagConstraints());

        pnlCover.add(tbl7, new java.awt.GridBagConstraints());

        tbl6.setBackground(new java.awt.Color(175, 175, 175));
        tbl6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl6.setToolTipText("Permission Management");
        tbl6.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl6.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl6.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl6MouseExited(evt);
            }
        });
        tbl6.setLayout(new java.awt.GridBagLayout());

        lblPermission4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission4.setToolTipText("Permission Management");
        lblPermission4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission4MouseExited(evt);
            }
        });
        tbl6.add(lblPermission4, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlCover.add(tbl6, gridBagConstraints);

        tbl9.setBackground(new java.awt.Color(175, 175, 175));
        tbl9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl9.setToolTipText("Account Management");
        tbl9.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl9.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl9.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl9MouseExited(evt);
            }
        });
        tbl9.setLayout(new java.awt.GridBagLayout());

        lblAcc15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc15.setToolTipText("Account Management");
        lblAcc15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcc15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcc15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcc15MouseExited(evt);
            }
        });
        tbl9.add(lblAcc15, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlCover.add(tbl9, gridBagConstraints);

        tbl3.setBackground(new java.awt.Color(175, 175, 175));
        tbl3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl3.setToolTipText("Account Management");
        tbl3.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl3.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl3.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl3MouseExited(evt);
            }
        });
        tbl3.setLayout(new java.awt.GridBagLayout());

        lblAcc14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc14.setToolTipText("Account Management");
        lblAcc14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcc14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcc14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcc14MouseExited(evt);
            }
        });
        tbl3.add(lblAcc14, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlCover.add(tbl3, gridBagConstraints);

        tbl10.setBackground(new java.awt.Color(175, 175, 175));
        tbl10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl10.setToolTipText("Account Management");
        tbl10.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl10.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl10.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl10MouseExited(evt);
            }
        });
        tbl10.setLayout(new java.awt.GridBagLayout());

        lblPermission10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission10.setToolTipText("Permission Management");
        lblPermission10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission10MouseExited(evt);
            }
        });
        tbl10.add(lblPermission10, new java.awt.GridBagConstraints());

        pnlCover.add(tbl10, new java.awt.GridBagConstraints());

        tbl12.setBackground(new java.awt.Color(175, 175, 175));
        tbl12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl12.setToolTipText("Permission Management");
        tbl12.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl12.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl12.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl12MouseExited(evt);
            }
        });
        tbl12.setLayout(new java.awt.GridBagLayout());

        lblPermission6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblPermission6.setToolTipText("Permission Management");
        lblPermission6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermission6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPermission6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermission6MouseExited(evt);
            }
        });
        tbl12.add(lblPermission6, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        pnlCover.add(tbl12, gridBagConstraints);

        tbl11.setBackground(new java.awt.Color(175, 175, 175));
        tbl11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl11.setToolTipText("Account Management");
        tbl11.setMaximumSize(new java.awt.Dimension(200, 100));
        tbl11.setMinimumSize(new java.awt.Dimension(200, 100));
        tbl11.setPreferredSize(new java.awt.Dimension(200, 100));
        tbl11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbl11MouseExited(evt);
            }
        });
        tbl11.setLayout(new java.awt.GridBagLayout());

        lblAcc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Table-icon.png"))); // NOI18N
        lblAcc4.setToolTipText("Account Management");
        lblAcc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcc4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcc4MouseExited(evt);
            }
        });
        tbl11.add(lblAcc4, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        pnlCover.add(tbl11, gridBagConstraints);

        getContentPane().add(pnlCover, new java.awt.GridBagConstraints());

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 24));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 213, 13, 13);
        getContentPane().add(btnCancel, gridBagConstraints);

        btnSetAvai.setText("Available");
        btnSetAvai.setPreferredSize(new java.awt.Dimension(100, 24));
        btnSetAvai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAvaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 213);
        getContentPane().add(btnSetAvai, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccMouseClicked

    private void lblAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccMouseEntered
        // TODO add your handling code here:
        // pnl104.setBackground(getBackground());
    }//GEN-LAST:event_lblAccMouseEntered

    private void lblAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccMouseExited
        // TODO add your handling code here:
        // pnlAccoun_item.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_lblAccMouseExited

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(1))) {
                tbl1.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseEntered
        // TODO add your handling code here:
        //evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl1MouseEntered

    private void tbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseExited
        // TODO add your handling code here:
        //pnlAccoun_item.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl1MouseExited

    private void lblPermission7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission7MouseClicked

    private void lblPermission7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission7MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission7MouseEntered

    private void lblPermission7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission7MouseExited

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(2))) {
                tbl2.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl2MouseClicked

    private void tbl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseEntered
        // TODO add your handling code here:
        //  evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl2MouseEntered

    private void tbl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseExited
        // TODO add your handling code here:
        //pnlPermission_item7.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl2MouseExited

    private void lblAcc10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc10MouseClicked
        // TODO add your handling code here:

        //addToSelectedList(tableModel.find("102"));
    }//GEN-LAST:event_lblAcc10MouseClicked

    private void lblAcc10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc10MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblAcc10MouseEntered

    private void lblAcc10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc10MouseExited

    private void tbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(5))) {
                tbl5.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl5MouseClicked

    private void tbl5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MouseEntered
        // TODO add your handling code here:
        ///  evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl5MouseEntered

    private void tbl5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MouseExited
        // TODO add your handling code here:
        //pnl102.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl5MouseExited

    private void lblAcc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc3MouseClicked

    private void lblAcc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc3MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblAcc3MouseEntered

    private void lblAcc3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc3MouseExited

    private void tbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(4))) {
                tbl4.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl4MouseClicked

    private void tbl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseEntered
        // TODO add your handling code here:
        //evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl4MouseEntered

    private void tbl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseExited
        // TODO add your handling code here:
        // pnlAccoun_item3.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl4MouseExited

    private void lblPermission8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission8MouseClicked

    private void lblPermission8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission8MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission8MouseEntered

    private void lblPermission8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission8MouseExited

    private void tbl8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl8MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {

            if (addToSelectedList(tableModel.find(8))) {
                tbl8.setBackground(Color.CYAN);
            }

        }
    }//GEN-LAST:event_tbl8MouseClicked

    private void tbl8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl8MouseEntered
        // TODO add your handling code here:
        //evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl8MouseEntered

    private void tbl8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl8MouseExited
        // TODO add your handling code here:
        //pnl101.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl8MouseExited

    private void lblPermission1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission1MouseClicked
        // TODO add your handling code here:
        //addToSelectedList(tableModel.find("201"));
    }//GEN-LAST:event_lblPermission1MouseClicked

    private void lblPermission1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission1MouseEntered
        // TODO add your handling code here:
        //evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission1MouseEntered

    private void lblPermission1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission1MouseExited

    private void tbl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(7))) {
                tbl7.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl7MouseClicked

    private void tbl7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MouseEntered
        // TODO add your handling code here:
        //  evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl7MouseEntered

    private void tbl7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MouseExited
        // TODO add your handling code here:
        // pnl201.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl7MouseExited

    private void lblPermission4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission4MouseClicked

    private void lblPermission4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission4MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission4MouseEntered

    private void lblPermission4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission4MouseExited

    private void tbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl6MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(6))) {
                tbl6.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl6MouseClicked

    private void tbl6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl6MouseEntered
        // TODO add your handling code here:
        //   evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl6MouseEntered

    private void tbl6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl6MouseExited
        // TODO add your handling code here:
        //  pnlPermission_item4.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl6MouseExited

    private void lblAcc15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc15MouseClicked

    private void lblAcc15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc15MouseEntered
        // TODO add your handling code here:
        //  evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblAcc15MouseEntered

    private void lblAcc15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc15MouseExited

    private void tbl9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl9MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(9))) {
                tbl9.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl9MouseClicked

    private void tbl9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl9MouseEntered
        // TODO add your handling code here:.
        //  evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl9MouseEntered

    private void tbl9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl9MouseExited
        // TODO add your handling code here:
        // pnlAccoun_item16.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl9MouseExited

    private void lblAcc14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc14MouseClicked

    private void lblAcc14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc14MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblAcc14MouseEntered

    private void lblAcc14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc14MouseExited

    private void tbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(3))) {
                tbl3.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl3MouseClicked

    private void tbl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseEntered
        // TODO add your handling code here:.
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl3MouseEntered

    private void tbl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseExited
        // TODO add your handling code here:
        //pnlAccoun_item15.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl3MouseExited

    private void lblPermission10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission10MouseClicked

    private void lblPermission10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission10MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission10MouseEntered

    private void lblPermission10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission10MouseExited

    private void tbl10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl10MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(10))) {
                tbl10.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl10MouseClicked

    private void tbl10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl10MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl10MouseEntered

    private void tbl10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl10MouseExited

    private void lblPermission6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission6MouseClicked

    private void lblPermission6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission6MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblPermission6MouseEntered

    private void lblPermission6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermission6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPermission6MouseExited

    private void tbl12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl12MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(12))) {
                tbl12.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl12MouseClicked

    private void tbl12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl12MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl12MouseEntered

    private void tbl12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl12MouseExited
        // TODO add your handling code here:
        //pnl301.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl12MouseExited

    private void lblAcc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc4MouseClicked

    private void lblAcc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc4MouseEntered
        // TODO add your handling code here:
        // evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_lblAcc4MouseEntered

    private void lblAcc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcc4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAcc4MouseExited

    private void tbl11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl11MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (addToSelectedList(tableModel.find(11))) {
                tbl11.setBackground(Color.CYAN);
            }
        }
    }//GEN-LAST:event_tbl11MouseClicked

    private void tbl11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl11MouseEntered
        // TODO add your handling code here:
        //evt.getComponent().setBackground(getBackground());
    }//GEN-LAST:event_tbl11MouseEntered

    private void tbl11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl11MouseExited
        // TODO add your handling code here:
        // pnlAccoun_item4.setBackground(Color.getColor("FFFFFF"));
    }//GEN-LAST:event_tbl11MouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < selectedList.size(); i++) {
            selectedList.remove(i);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSetAvaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetAvaiActionPerformed
        // TODO add your handling code here:
        for (RestaurantTable r : selectedList) {
            tableModel.find(r.getTableId()).setStatus(1);
        }
        loadData();

        for (int i = 0; i < selectedList.size(); i++) {
            selectedList.remove(i);
        }
    }//GEN-LAST:event_btnSetAvaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSetAvai;
    private javax.swing.JLabel lblAcc;
    private javax.swing.JLabel lblAcc10;
    private javax.swing.JLabel lblAcc14;
    private javax.swing.JLabel lblAcc15;
    private javax.swing.JLabel lblAcc3;
    private javax.swing.JLabel lblAcc4;
    private javax.swing.JLabel lblPermission1;
    private javax.swing.JLabel lblPermission10;
    private javax.swing.JLabel lblPermission4;
    private javax.swing.JLabel lblPermission6;
    private javax.swing.JLabel lblPermission7;
    private javax.swing.JLabel lblPermission8;
    private javax.swing.JPanel pnlCover;
    private javax.swing.JPanel tbl1;
    private javax.swing.JPanel tbl10;
    private javax.swing.JPanel tbl11;
    private javax.swing.JPanel tbl12;
    private javax.swing.JPanel tbl2;
    private javax.swing.JPanel tbl3;
    private javax.swing.JPanel tbl4;
    private javax.swing.JPanel tbl5;
    private javax.swing.JPanel tbl6;
    private javax.swing.JPanel tbl7;
    private javax.swing.JPanel tbl8;
    private javax.swing.JPanel tbl9;
    // End of variables declaration//GEN-END:variables
}
